### ISSUE TITLE
【教程】less 

### ISSUE THREAD

**Issue by ryu2gaku** [ryu2gaku/my-notes#11]

**Comment by ryu2gaku** [comment]
## <a id="note-1"></a>变量 variable

``` less
@nice-blue: #5B83AD;
@light-blue: @nice-blue + #111; 

#header {
  color: @light-blue;
} 
```
> 由于变量只能定义一次，其本质就是“常量” 

选择器 

``` less
@my-selector: banner;

.@{my-selector} { margin: 0 auto; }
```
URL 

``` less
@images: "../img";

body { background: url("@{images}/white-sand.png"); }
```
属性 

``` less
@property: color;

.widget {
  @{property}: #0ee;
  background-@{property}: #999;
}
```
@import 语句

``` less
@themes: "../../src/themes";
	
@import "@{themes}/tidal-wave.less";
```
**变量名** 

``` less
@fnord:  "I am fnord.";
@var:    "fnord";
content: @@var; 

// 编译结果 
// content: "I am fnord.";
```
**延迟加载** Lazy Loading 

> 变量是延迟加载的，在使用前不一定要预先声明 

``` less
// 合法 
.lazy-eval {
  width: @var;
}

@var: @a;
@a: 9%; 

// 同样合法
.lazy-eval-scope {
  width: @var;
  @a: 9%;
}

@var: @a;
@a: 100%; 

// 编译结果 
// .lazy-eval-scope { width: 9%; }
```
> 如果对同一个变量定义两次的话，在当前作用域中最后一次定义的将被使用。
 
``` less
@var: 0;
.class1 {
  @var: 1;
  .class {
    @var: 2;
    three: @var;
    @var: 3;
  }
  one: @var;
}

// 编译结果
// .class1 .class { three: 3; }
// .class { one: 1; }
```

**Comment by ryu2gaku** [comment]
## <a id="note-2"></a>Mixin

> "mix-in" properties from existing styles  

``` less
.a, #b {
  color: red;
}
.mixin-class {
  .a();
}
.mixin-id {
  #b();
}

// 编译结果
// .a, #b { color: red; }
// .mixin-class { color: red; }
// .mixin-id { color: red; }
```
> 注意：在调用 mixin 时，括号是可选的。`.a();` 和 `.a;` 两个语句做了相同的事情。 

**不带输出的 mixin**

> 在不想输出的 mixin 的名字后面加上一个括号，就可以实现 

``` less
.my-mixin {
  color: black;
}
.my-other-mixin() {
  background: white;
}
.class {
  .my-mixin;
  .my-other-mixin;
} 

// 编译结果 
// .my-mixin { color: black; } 
// .class { color: black; background: white; }
```
**带选择器的 mixin** 

``` less
.my-hover-mixin() {
  &:hover {
    border: 1px solid red;
  }
}
button {
  .my-hover-mixin();
}

// 编译结果
// button:hover { border: 1px solid red; }
```
**带参数的 mixin**

``` less
.border-radius(@radius) {
  -webkit-border-radius: @radius;
     -moz-border-radius: @radius;
          border-radius: @radius;
}

#header {
  .border-radius(4px);
} 

// 编译结果
// #header {
//   -webkit-border-radius: 4px;
//      -moz-border-radius: 4px;
//           border-radius: 4px;
// }
```
带参数并且有默认值 

``` less
.border-radius(@radius: 5px) {
  -webkit-border-radius: @radius;
     -moz-border-radius: @radius;
          border-radius: @radius;
}

#header {
  .border-radius;
}
```
带多个参数的 mixin  

``` less
// 1. 参数之间可以使用分号（;）或逗号分隔（,）
// 2. 推荐使用分号（;）
// 3. 逗号（,）有两个意思：mixin 参数分隔符，css 列表分隔符  

.mixin(@param1 ; @param2: val2 ; @param3: val3) {
  color: @param1;
  padding: @param2;
  margin: @param3 @param3 @param3 @param3;
} 

.div1 {
  // 两个参数, 并且每个参数都是逗号分隔的列表
  .mixin(1, 2, 3; something, else);
}  
.div2 {
  // 三个参数, 并且每个参数都包含一个数字
  .mixin(1, 2, 3);
}
.div3 {
  // 使用分号, 一个参数, 参数包含一个逗号分隔的 css 列表
  .mixin(1, 2, 3;);
}

// 编译结果
// .div1 {
//   color: 1, 2, 3;
//   padding: something, else;
//   margin: val3 val3 val3 val3;
// }
// .div2 {
//   color: 1;
//   padding: 2;
//   margin: 3 3 3 3;
// }
// .div3 {
//   color: 1, 2, 3;
//   padding: val2;
//   margin: val3 val3 val3 val3;
// }
```
定义多个具有相同名称和参数数量的 mixin 

> 定义多个具有相同名称和参数数量的 mixin 是合法的。less 会使用它可以应用的属性。

``` less
.mixin(@color) {
  color-1: @color;
}
.mixin(@color; @padding:2) {
  color-2: @color;
  padding-2: @padding;
}
.mixin(@color; @padding; @margin: 2) {
  color-3: @color;
  padding-3: @padding;
  margin: @margin @margin @margin @margin;
} 

.some .selector div {
  .mixin(#008000);
}  

// 编译结果 
// .some .selector div { color-1: #008000; color-2: #008000; padding-2: 2; }
```

**命名参数** 

> 引用 mixin 时，可以通过参数名称，而不是参数的位置来为 mixin 提供参数值。

``` less
.mixin(@color: black; @margin: 10px; @padding: 20px) {
  color: @color;
  margin: @margin;
  padding: @padding;
} 

.class1 {
  .mixin(@margin: 20px; @color: #33acfe);
}
.class2 {
  .mixin(#efca44; @padding: 40px);
} 

// 编译结果 
// .class1 {
//   color: #33acfe;
//   margin: 20px;
//   padding: 20px;
// }
// .class2 {
//   color: #efca44;
//   margin: 10px;
//   padding: 40px;
// }
```
**@arguments 变量**

``` less
// @arguments 代表所有的可变参数 
// 参数的先后顺序就是你的括号内的参数的先后顺序  

.box-shadow(@x: 0; @y: 0; @blur: 1px; @color: #000) {
  -webkit-box-shadow: @arguments;
     -moz-box-shadow: @arguments;
          box-shadow: @arguments;
} 

.big-block {
  .box-shadow(2px; 5px);
} 

// 编译结果
// .big-block {
//   -webkit-box-shadow: 2px 5px 1px #000;
//      -moz-box-shadow: 2px 5px 1px #000;
//           box-shadow: 2px 5px 1px #000;
// }
```
**匹配模式**

传值的时候定义一个字符，在使用的时候使用哪个字符，就调用哪条规则。 

``` less
// 要求第一个参数为 dark 
.mixin(dark; @color) {  
  color: darken(@color, 10%);
}
// 要求第一个参数为 light
.mixin(light; @color) { 
  color: lighten(@color, 10%);
}
// 第一个参数可以为任意值
.mixin(@_; @color) {
  display: block;
} 

@switch: light;
.class {
  .mixin(@switch; #888);
}

// 编译结果
// .class { color: #a2a2a2; display: block; }
```

**作为函数使用的 mixin** 

> 从 mixin 返回变量  

``` less
// 定义在 mixin 中的所有变量，在调用者的作用域中都是可用的
.mixin() {
  @width:  100%;
  @height: 200px;
}
	
.caller {
  .mixin();
  width:  @width;
  height: @height;
}
```
``` less
// 因此，定义在 mixin 中的变量可以扮演返回值的角色
.average(@x, @y) {
  @average: ((@x + @y) / 2);
}
	
div {
  .average(16px, 50px); // "call" the mixin
  padding: @average;    // use its "return" value
}
```

**Comment by ryu2gaku** [comment]
## <a id="note-3"></a>嵌套规则 

``` less
#header {
  color: black;
  .navigation {
    font-size: 12px;
  }
  .logo {
    width: 300px;
  }
} 

// 编译结果
// #header { color: black; } 
// #header .navigation { font-size: 12px; }
// #header .logo { width: 300px; } 
```
**使用 `&` 引用父元素选择器**  

``` less
a {
  color: blue;
  &:hover {
    color: green;
  }
}

// 编译结果
// a { color: blue; }
// a:hover { color: green; }
```
``` less
.button {
  &-ok {
    background-image: url("ok.png");
  }
  &-cancel {
    background-image: url("cancel.png");
  }
  &-custom {
    background-image: url("custom.png");
  }
} 

// 编译结果
// .button-ok { background-image: url("ok.png"); }
// .button-cancel { background-image: url("cancel.png"); }
// .button-custom { background-image: url("custom.png"); }
```
``` less
.link {
  & + & {
    color: red;
  }
  & & {
    color: green;
  }
  && {
    color: blue;
  }
  &, &ish {
    color: cyan;
  }
}

// 编译结果
// .link + .link { color: red; }
// .link .link { color: green; }
// .link.link { color: blue; }
// .link, .linkish { color: cyan; }
```
`&` 指代所有的父元素  

``` less
.grand {
  .parent {
    & > & {
      color: red;
    }
    & & {
      color: green;
    }
    && {
      color: blue;
    }
    &, &ish {
      color: cyan;
    }
  }
}

// 编译结果
// .grand .parent > .grand .parent { color: red; }
// .grand .parent .grand .parent { color: green; }
// .grand .parent.grand .parent { color: blue; }
// .grand .parent, .grand .parentish { color: cyan; }
```
改变选择器顺序  

``` less
.header {
  .menu {
    border-radius: 5px;
    .no-borderradius & {
    // 将 & 放到当前选择器之后，就会将当前选择器插入到所有的父选择器之前
      background-image: url('images/button-background.png');
    }
  }
}

// 编译结果
// .header .menu { border-radius: 5px; }
// .no-borderradius .header .menu { background-image: url('images/button-background.png'); }
```
`&` 也可以被用来生成逗号分隔的选择器列的每一个可能的排列 

``` less
p, a, ul, li {
border-top: 2px dotted #366;
  & + & {
      border-top: 0;
  } 
} 

// 编译结果
// p, a, ul, li { border-top: 2px dotted #366; }
// p + p, p + a, p + ul, p + li, a + p, a + a, a + ul, a + li, ul + p, ul + a, ul + ul, ul + li, li + p, li + a, li + ul, li + li { border-top: 0; }
```

**Comment by ryu2gaku** [comment]
## <a id="note-4"></a>运算

任何数字、颜色或者变量都可以参与运算。

### 数值型运算

less 会自动推断数值的单位，所以不必每一个值都加上单位。

``` less
.container {
  width: 200px + 300;
}

// 编译结果
// .container { width: 500px; }
```
### 颜色值运算  

less 运算时，先将颜色值转换为 rgb 模式，然后在转换为 16 进制的颜色值并且返回。 

```less
.container {
  color: #000000 + 30;
} 

// 编译结果
// .container { color: #1e1e1e; }
```

**Comment by ryu2gaku** [comment]
## <a id="note-5"></a>命名空间 

``` less
#outer {
  .inner {
    color: red;
  }
} 

.c {
  #outer > .inner;
}

// 符号 `>` 是可选的，下面都做了相同的事情  
// #outer > .inner;
// #outer > .inner();
// #outer.inner;
// #outer.inner();

// 将你的 mixin 放在一个 id 或 class 选择器下, 可以确保不和其他的库起冲突  
#my-library {
  .my-mixin() {
    color: black;
  }
}
// 使用时如下
.class {
  #my-library > .my-mixin();
}
```

**Comment by ryu2gaku** [comment]
## <a id="note-6"></a>作用域 

less 中的作用域与编程语言中的作用域概念非常相似，首先会在局部查找变量和 mixin，如果没找到，编译器就会在父作用域中查找，依次类推。

```less
@var: red;
	
#page {
  @var: white;
  #header {
    color: @var; // white
  }
}
```

**Comment by ryu2gaku** [comment]
## <a id="note-6"></a>条件表达式

``` less
// `when` 关键词
.mixin (@a) when (lightness(@a) >= 50%) {
  background-color: black;
}
.mixin (@a) when (lightness(@a) < 50%) {
  background-color: white;
}
.mixin (@a) {
  color: @a;
} 

.class1 { .mixin(#ddd) }
.class2 { .mixin(#555) }

// 编译结果
// .class1 { background-color: black; color: #ddd; }
// .class2 { background-color: white; color: #555; } 

// `true` 关键词
// `>` `>=` `=` `<=` `<` 比较运算符 
```
## 循环 

``` less
.loop(@counter) when (@counter > 0) {
  .loop((@counter - 1));    // next iteration
  width: (10px * @counter); // code for each iteration
}
div {
  .loop(5); // launch the loop
}  

// 编译结果
// div {
//   width: 10px;
//   width: 20px;
//   width: 30px;
//   width: 40px;
//   width: 50px;
// }
```
## 合并 Merge  

能够聚合多个属性从而形成一个用逗号分隔的单一属性。对于像 `background` 和 `transform` 这类属性非常有用。

**逗号**   

``` less 
// 在每个需要合并的属性名后面添加一个 `+` 以作标示 
.mixin() {
  box-shadow+: inset 0 0 10px #555;
}
.myclass {
  .mixin();
  box-shadow+: 0 0 20px black;
} 

// 编译结果
// .myclass { box-shadow: inset 0 0 10px #555, 0 0 20px black; }
```
**空格** 

``` less
// 在每个需要合并的属性名后面添加一个 `+_` 以作标示 
.mixin() {
  transform+_: scale(2);
}
.myclass {
  .mixin();
  transform+_: rotate(15deg);
}

// 编译结果
// .myclass { transform: scale(2) rotate(15deg); }
```

## 函数 

[函数手册](http://less.bootcss.com/functions/)
